version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: ai-chatbot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aichatbot
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aichatbot"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pgdata:
